version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster
    parameters:
      platform:
        type: string
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - checkout
      - setup_remote_docker
      - run:
          name: Setup
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy2
            # echo "$DOCKER_REDISFAB_PWD" | docker login --username redisfab --password-stdin
            docker login --username redisfab --password "$DOCKER_REDISFAB_PWD"
      - run:
          name: Build and publish
          command: |
            make build X64=1 OSNICK=<<parameters.platform>>
            if [[ $CIRCLE_BRANCH == master ]]; then
                make publish X64=1 OSNICK=<<parameters.platform>>
            fi
          no_output_timeout: 30m


on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-master-and-version-tags: &on-master-and-version-tags
  filters:
    branches:
      only:
        - master
    tags:
      only: /^v[0-9].*/


workflows:
  version: 2
  build_all:
    jobs:
      - build:
          name: build-buster
          platform: buster
          <<: *on-any-branch
      - build:
          name: build-centos7
          platform: centos7
          <<: *on-any-branch
      - build:
          name: build-bionic
          platform: bionic
          <<: *on-any-branch
      - build:
          name: build-xenial
          platform: xenial
          <<: *on-any-branch
      - build:
          name: build-trusty
          platform: trusty
          <<: *on-any-branch
  weekly:
    triggers:
      - schedule:
          # Run on Sundat 21:17 [M H DoM M DoW]
          cron: "21 17 * * 0"
          <<: *on-master
    jobs:
      - build:
          name: build-buster
          platform: buster
      - build:
          name: build-centos7
          platform: centos7
      - build:
          name: build-bionic
          platform: bionic
      - build:
          name: build-xenial
          platform: xenial
      - build:
          name: build-trusty
          platform: trusty
